server:
  port: 8081
spring:
  http:
    encoding:
      charset: "UTF-8"
  jackson:
    time-zone: "America/Lima"
    date-format: "yyyy-MM-dd"
    timestamp-format: "yyyy-MM-dd HH:mm:ss"
  datasource:
    url: jdbc:h2:mem:customers
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: "org.hibernate.dialect.H2Dialect"
    type: "com.zaxxer.hikari.HikariDataSource"
    hikari:
      connection-timeout : 20000 #maximum number of milliseconds that a client will wait for a connection
      maximum-idle: 3 # Maximum number of idle connections mantained by Hikari
      minimum-idle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 3 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics