---
micronaut:
  application:
    name: customers-micronaut

---
datasources.default: {}
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
    type: "com.zaxxer.hikari.HikariDataSource"
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      maximum-idle: 3 # Maximum number of idle connections mantained by Hikari
      minimum-idle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 3 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

